# Generated by Django 6.0.4 on 2026-05-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('hours', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Open Now', max_length=50)),
                ('services', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
