# Generated by Django 6.0.4 on 2026-05-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_friday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_monday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_saturday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_sunday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_thursday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_tuesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clinic',
            name='open_wednesday',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='clinic',
            table='clinics',
        ),
    ]
